<?php

/**
 * @file
 * Preprocess functions for Business Affairs Subtheme.
 */

/**
 * Prepares variables for the html.html.twig template.
 */
function businessaffairs_subtheme_preprocess_html(&$variables) {
  $variables['stanford_basic_path'] = \Drupal::service('extension.list.theme')->getPath('stanford_basic');
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function businessaffairs_subtheme_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if (!empty($variables['elements']['#id']) && $variables['elements']['#id'] == 'businessaffairs_subtheme_search') {
    $suggestions[] = 'block__stanford_basic_search';
  }
}

function businessaffairs_subtheme_preprocess_paragraph__stanford_banner(&$variables) {
  /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
  $paragraph = $variables['paragraph'];
  $variables['attributes']['class'][] = $paragraph->getBehaviorSetting('react_paragraphs:banner_variant_info', 'banner_style');
}

function businessaffairs_subtheme_preprocess_paragraph__stanford_page_title_banner(&$variables) {
  /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
  $paragraph = $variables['paragraph'];
  $variables['attributes']['class'][] = $paragraph->getBehaviorSetting('react_paragraphs:page_title_variant_info', 'banner_style');
}
